version: "3"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
