FROM wordpress:latest

# Copy your custom WordPress files if needed (themes, plugins, etc.)
# COPY ./custom_theme /var/www/html/wp-content/themes/custom_theme/
# COPY ./custom_plugin /var/www/html/wp-content/plugins/custom_plugin/

# You can also copy your wp-config.php if needed
# COPY ./wp-config.php /var/www/html/wp-config.php
COPY ./wordpress_data /var/www/html/
