apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-deployment
  namespace: default
  labels:
    app: doc30
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doc30
  template:
    metadata:
      labels:
        app: doc30
    spec:
      restartPolicy: Always
      containers:
      - name: doc30
        image: docker.io/dedkola/doc30:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: doc30-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: doc30
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
