services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
      - prometheus-data:/prometheus  
    networks:
      - monitoring 

volumes:
  prometheus-data:
    driver: local  

networks:
  monitoring:
    driver: bridge  