services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration file
      - prometheus-data:/prometheus  # Persistent storage for metrics data
    networks:
      - monitoring  # Custom network for LAN access

volumes:
  prometheus-data:
    driver: local  # Persistent volume for Prometheus data

networks:
  monitoring:
    driver: bridge  # Bridge network for LAN communication